config/routes.rb
Rails.application.routes.draw do
  root "artists#index"

  resources :artists, only: :show
  resources :albums, only: %i(index show)
  resources :songs, only: %i(index show)
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :load_artist, only: :index
  before_action :load_album, only: :show

  before_action :add_breadcrumb_artist_path
  before_action :add_breadcrumb_albums_path
  before_action :add_breadcrumb_album_path, only: :show

  def index
    @albums = @artist.albums
  end

  def show
  end

  private

  def load_artist
    @artist = Artist.find_by id: params[:artist_id]

    redirect_to root_url unless @artist
  end

  def load_album
    @album = Album.find_by id: params[:id]
    redirect_back(fallback_location: root_url) unless @album

    @artist = @album.artist
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include AddBreadcrumbHelper
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :load_artist, only: :show
  before_action :add_breadcrumb_artist_path, only: :show

  def index
    @artists = Artist.all
  end

  def show
  end

  private

  def load_artist
    @artist = Artist.find_by id: params[:id]

    redirect_to root_url unless @artist
  end
end

app/controllers/concerns/add_breadcrumb_helper.rb
module AddBreadcrumbHelper extend ActiveSupport::Concern
  included do
    before_action :add_breadcrumb_root_path
  end

  def add_breadcrumb_root_path
    add_breadcrumb "Home", :root_path
  end

  def add_breadcrumb_artist_path
    add_breadcrumb "Artist #{@artist.name}", "/artists/#{@artist.id}"
  end

  def add_breadcrumb_albums_path
    add_breadcrumb "Albums", "/albums?artist_id=#{@artist.id}"
  end

  def add_breadcrumb_album_path
    add_breadcrumb "Album #{@album.name}", "/albums/#{@album.id}"
  end

  def add_breadcrumb_songs_path
    add_breadcrumb "Songs", "/songs?album_id=#{@album.id}"
  end

  def add_breadcrumb_song_path
    add_breadcrumb "Song #{@song.name}", "/songs/#{@song.id}"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :load_album, only: :index
  before_action :load_song, only: :show

  before_action :add_breadcrumb_artist_path
  before_action :add_breadcrumb_albums_path
  before_action :add_breadcrumb_album_path
  before_action :add_breadcrumb_songs_path
  before_action :add_breadcrumb_song_path, only: :show

  def index
    @songs = @album.songs
  end

  def show
  end

  private

  def load_album
    @album = Album.find_by id: params[:album_id]
    redirect_back(fallback_location: root_url) unless @album

    @artist = @album.artist
  end

  def load_song
    @song = Song.find_by id: params[:id]
    redirect_back(fallback_location: root_url) unless @song

    @album = @song.album
    @artist = @album.artist
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<div class="container">
  <h2>Albums</h2>
  <p>by artist <%= link_to @artist.name, @artist %></p>

  <table class="table">
    <thead>
      <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Description</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @albums.each do |album| %>
        <tr>
          <td><%= album.id %></td>
          <td><%= album.name %></td>
          <td><%= album.description %></td>
          <td><%= link_to "View", album, class: "btn btn-sm btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/albums/show.html.erb
<div class="container">
  <h2>Album <%= @album.name %></h2>
  <p>by artist <%= link_to @artist.name, @artist %></p>

  <div class="panel panel-default">
    <div class="panel-heading">
      Name: <%= @album.name %>
    </div>
    <div class="panel-body">
      <%= @album.description %>

      <p style="margin: 10px 0;">
        <%= link_to "View all songs", songs_path(album_id: @album.id) %>
      </p>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="container">
  <h2>Artists</h2>

  <table class="table">
    <thead>
      <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Description</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @artists.each do |artist| %>
        <tr>
          <td><%= artist.id %></td>
          <td><%= artist.name %></td>
          <td><%= artist.description %></td>
          <td><%= link_to "View", artist, class: "btn btn-sm btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/artists/show.html.erb
<div class="container">
  <h2>Artist <%= @artist.name %></h2>

  <div class="panel panel-default">
    <div class="panel-heading">
      Name: <%= @artist.name %>
    </div>
    <div class="panel-body">
      <%= @artist.description %>

      <p style="margin: 10px 0;">
        <%= link_to "View all albums", albums_path(artist_id: @artist.id) %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoBreadcrumbsOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div class="container">
      <ol class="breadcrumb">
        <%= render_breadcrumbs tag: "li class='breadcrumb-item'", separator: "" %>
      </ol>
    </div>
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<div class="container">
  <h2>Songs</h2>
  <p>by artist <%= link_to @artist.name, @artist %> in album <%= link_to @album.name, @album %></p>

  <table class="table">
    <thead>
      <tr>
        <td>Id</td>
        <td>Name</td>
        <td>Description</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @songs.each do |song| %>
        <tr>
          <td><%= song.id %></td>
          <td><%= song.name %></td>
          <td><%= song.description %></td>
          <td><%= link_to "View", song, class: "btn btn-sm btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/songs/show.html.erb
<div class="container">
  <h2>Song <%= @song.name %></h2>
  <p>by artist <%= link_to @artist.name, @artist %> in album <%= link_to @album.name, @album %></p>

  <div class="panel panel-default">
    <div class="panel-heading">
      Name: <%= @song.name %>
    </div>
    <div class="panel-body">
      <%= @song.description %>

      <div>
        Lyric:
        <ul>
          <% @song.lyric.split("<br>").each do |line| %>
            <li><%= line %></li>
          <% end %>
        </ul>
      <div>
    </div>
  </div>
</div>